version: "3.9"
services:
  resnet-model:
    image: zoomcamp-10-model:resnet
  gateway:
    image: zoomcamp-10-gateway:002
    environment:
      - TF_SERVING_HOST=resnet-model:8500
    ports:
      - "9696:9696"